- platform: meteo_france
  postal_code: '37000'
  name: meteo
  monitored_conditions:
    - temperature
    - weather
    - wind_speed
    - uv
    - next_rain
    - freeze_chance
    - rain_chance
    - snow_chance
    - thunder_chance

- platform: darksky
  api_key: 18aca8cb7b41392a525aaacf971ae939
  name: DarkSky
  monitored_conditions:
    - summary
    - icon
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_gust
    - wind_bearing
    - humidity
    - pressure
    - visibility
    - ozone
    - uv_index
    - nearest_storm_distance
    - nearest_storm_bearing


- platform: mqtt
  state_topic: "home/garden/temperature"
  name: "MQTT cpt Temperature"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: "home/lovelace/luminosite"
  name: "MQTT cpt Luminosite"
  unit_of_measurement: 'lum'
  value_template: '{{ value_json.luminosite }}'
